language: node_js
notifications:
  email: false
cache: npm
branches:
  only:
    - master
script: "npm run build"
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: _site
  github_token: $GITHUB_TOKEN
  keep-history: true
  fqdn: windingtree.com
  on:
    branch: master
