language: ruby
rvm:
- 2.5.1
notifications:
  email: false
branches:
  only:
    - master
script: "bundle exec jekyll build JEKYLL_ENV=production"
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: _site
  github_token: $GITHUB_TOKEN
  keep-history: true
  fqdn: windingtree.com
  on:
    branch: master
