title: Winding Tree

baseurl: ''

exclude:
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
    - .idea
    - Gemfile
    - Gemfile.lock
    - gulpfile.babel.js
    - node_modules
    - package.json
    - yarn.lock
    - modernizr-custom.json

sass:
    sass_dir: _sass
    style: compressed
