title: Winding Tree

baseurl: /winding-tree

exclude:
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
    - .idea
    - node_modules
    - package.json
    - modernizr-custom.json
    - yarn.lock

sass:
    sass_dir: _sass
